# Generated by Django 4.0.1 on 2022-01-30 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('othersName', models.CharField(blank=True, max_length=200, null=True)),
                ('othersLastName', models.CharField(blank=True, max_length=200, null=True)),
                ('numberId', models.CharField(max_length=30, null=True)),
                ('profession', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=1200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='kindId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.AddField(
            model_name='candidate',
            name='kindId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.kindid'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL),
        ),
    ]
