# Generated by Django 4.0.1 on 2022-01-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_states_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
