# Generated by Django 4.0.1 on 2022-01-31 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_candidate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='kindId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.kindid'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='numberId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profession',
            field=models.CharField(max_length=500),
        ),
    ]
