# Generated by Django 4.0.1 on 2022-01-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_candidate_kindid_alter_candidate_numberid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
