# Generated by Django 4.0.1 on 2022-01-31 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_offers_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
