# Generated by Django 4.0.1 on 2022-01-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_rename_states_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='API.state'),
        ),
    ]
