# Generated by Django 4.0.1 on 2022-01-31 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_offers_salary_alter_offers_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='API.candidate')),
                ('offers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='API.offers')),
            ],
        ),
    ]
