# Generated by Django 4.0.1 on 2022-01-31 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_offers_creatoruser_offers_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='state',
            field=models.ForeignKey(default='Activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='API.state'),
        ),
    ]
